version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - postgres.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  chainlink:
    image: smartcontract/chainlink:1.11.0
    env_file:
      - chainlink.env
    command: local node
    restart: on-failure
    ports:
      - 6688:6688
    links:
      - db
    depends_on:
      - db
    volumes:
      - chainlink_data:/chainlink

volumes:
  db-data:
  chainlink_data:
