version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data
  chainlink:
    build: .
    env_file:
      - chainlink.env
    command: local node -p /chainlink-config/.password -a /chainlink-config/.api
    restart: on-failure
    ports:
      - 6688:6688
    links:
      - db
    depends_on:
      - db
    volumes:
      - ~/.chainlink-ropsten:/chainlink

volumes:
  db-data:
