version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - postgres.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  chainlink:
    build: .
    env_file:
      - chainlink.env
    command: local node -p ~/chainlink/.password -a ~/chainlink/.api
    restart: on-failure
    ports:
      - 6688:6688
    links:
      - db
    depends_on:
      - db
    volumes:
      - ~/.chainlink-goerli:~/chainlink

volumes:
  db-data:
